version: '2.1'
services:
  merdaccio:
    build: .
    container_name: merdaccio
    environment:
      - merdaccio_PORT
    ports:
      - $merdaccio_PORT:$merdaccio_PORT
    volumes:
      - merdaccio-storage:/merdaccio/storage
volumes:
  merdaccio:
    driver: local
